[2023-12-04T04:15:21.099+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crone_exp.first scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2023-12-04T04:15:21.319+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crone_exp.first scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2023-12-04T04:15:21.320+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-12-04T04:15:22.139+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first> on 2023-12-02 00:00:00+00:00
[2023-12-04T04:15:22.672+0000] {standard_task_runner.py:57} INFO - Started process 206 to run task
[2023-12-04T04:15:22.669+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crone_exp', 'first', 'scheduled__2023-12-02T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/xcom.py', '--cfg-path', '/tmp/tmp8q3ane5r']
[2023-12-04T04:15:22.689+0000] {standard_task_runner.py:85} INFO - Job 184: Subtask first
[2023-12-04T04:17:38.849+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T04:17:39.504+0000] {dagrun.py:743} ERROR - Failed to get task for ti <TaskInstance: crone_exp.bash_1 scheduled__2023-12-02T00:00:00+00:00 [queued]>. Marking it as removed.
[2023-12-04T04:17:39.524+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
