[2023-11-30T12:58:45.421+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aa.download_s3_file_task manual__2023-11-30T12:58:17.791715+00:00 [queued]>
[2023-11-30T12:58:45.589+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aa.download_s3_file_task manual__2023-11-30T12:58:17.791715+00:00 [queued]>
[2023-11-30T12:58:45.607+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-30T12:58:45.720+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_s3_file_task> on 2023-11-30 12:58:17.791715+00:00
[2023-11-30T12:58:45.900+0000] {standard_task_runner.py:57} INFO - Started process 2384 to run task
[2023-11-30T12:58:45.917+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'aa', 'download_s3_file_task', 'manual__2023-11-30T12:58:17.791715+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/aa.py', '--cfg-path', '/tmp/tmpuxgj140l']
[2023-11-30T12:58:45.934+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask download_s3_file_task
[2023-11-30T12:58:46.874+0000] {task_command.py:416} INFO - Running <TaskInstance: aa.download_s3_file_task manual__2023-11-30T12:58:17.791715+00:00 [running]> on host ef0d87b1d156
[2023-11-30T12:58:48.063+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dashrath' AIRFLOW_CTX_DAG_ID='aa' AIRFLOW_CTX_TASK_ID='download_s3_file_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T12:58:17.791715+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T12:58:17.791715+00:00'
[2023-11-30T12:58:48.107+0000] {s3.py:1366} INFO - This function shadows the 'download_file' method of S3 API, but it is not the same. If you want to use the original method from S3 API, please call 'S3Hook.get_conn().download_file()'
[2023-11-30T12:58:48.138+0000] {s3.py:1372} INFO - Downloading source S3 file from Bucket data,csv with path dummy-v1
[2023-11-30T12:58:48.477+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-11-30T12:58:48.478+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from login and password.
[2023-11-30T12:59:13.576+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/aa.py", line 22, in download_s3_file
    s3_hook.download_file(bucket_name, key,filename)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1375, in download_file
    s3_obj = self.get_key(key, bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 932, in get_key
    obj.load(**sanitize_extra_args())
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/resources/factory.py", line 564, in do_action
    response = action(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 928, in _make_api_call
    api_params = self._emit_api_params(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1043, in _emit_api_params
    self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/handlers.py", line 284, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "data,csv": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2023-11-30T12:59:14.128+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=aa, task_id=download_s3_file_task, execution_date=20231130T125817, start_date=20231130T125845, end_date=20231130T125914
[2023-11-30T12:59:14.555+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 109 for task download_s3_file_task (Parameter validation failed:
Invalid bucket name "data,csv": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"; 2384)
[2023-11-30T12:59:14.745+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T12:59:15.141+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
